name: pbc-notebook-dev
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - qiskit
      - qiskit-aer
      - matplotlib
      - pylatexenc
      - jupyter
      - pytest
      - pre-commit
      - black 
      - nbstripout
      - nbqa
